version: '3'
services:
  server:
    build:
      context: ./
      args:
        PORT: ${EXPOSE_PORT}
    networks:
      domain_net:
        ipv4_address: ${IPv4_ADDRESS}
    environment:
      PORT: ${PORT_PROD}
      ADDRESS: ${ADDRESS_PROD}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN_PROD}
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}
networks:
  domain_net:
    external: true